// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func initUserStore(uri string) (*UserStore, func(), error) {
	db, cleanup, err := ProvideDB(uri)
	if err != nil {
		return nil, nil, err
	}
	userStoreConfig := ProvideUserStoreDefaultConfig()
	userStore, cleanup2, err := ProvideUserStore(db, userStoreConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return userStore, func() {
		cleanup2()
		cleanup()
	}, nil
}
